package com.ainsigne.mobilesocialblogapp.ui.feeddetails

import com.ainsigne.mobilesocialblogapp.data.DataInjector
import com.ainsigne.mobilesocialblogapp.manager.ServicesInjector
import com.ainsigne.mobilesocialblogapp.manager.APIManager
import com.ainsigne.mobilesocialblogapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface FeedDetailsInjector {
    fun inject(fragment: FeedDetailsFragment)
}


/**
 * FeedDetailsInjector injector implementation of the protocol template for injection
 **/
class FeedDetailsInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : FeedDetailsFragment generated by the MVPTemplate
     **/
    fun inject(fragment: FeedDetailsFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter =
            FeedDetailsPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
