package com.ainsigne.mobilesocialblogapp.ui.chatsession

import com.ainsigne.mobilesocialblogapp.data.DataInjector
import com.ainsigne.mobilesocialblogapp.manager.ServicesInjector
import com.ainsigne.mobilesocialblogapp.manager.APIManager
import com.ainsigne.mobilesocialblogapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface ChatSessionInjector {
    fun inject(fragment: ChatSessionFragment)
}


/**
 * ChatSessionInjector injector implementation of the protocol template for injection
 **/
class ChatSessionInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : ChatSessionFragment generated by the MVPTemplate
     **/
    fun inject(fragment: ChatSessionFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter =
            ChatSessionPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
