package com.ainsigne.mobilesocialblogapp.ui.discover

import com.ainsigne.mobilesocialblogapp.data.DataInjector
import com.ainsigne.mobilesocialblogapp.manager.ServicesInjector
import com.ainsigne.mobilesocialblogapp.manager.APIManager
import com.ainsigne.mobilesocialblogapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface DiscoverInjector {
    fun inject(fragment: DiscoverFragment)
}


/**
 * DiscoverInjector injector implementation of the protocol template for injection
 **/
class DiscoverInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : DiscoverFragment generated by the MVPTemplate
     **/
    fun inject(fragment: DiscoverFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter =
            DiscoverPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
