package com.ainsigne.mobilesocialblogapp.sample

import com.ainsigne.mobilesocialblogapp.data.DataInjector
import com.ainsigne.mobilesocialblogapp.manager.ServicesInjector
import com.ainsigne.mobilesocialblogapp.manager.APIManager
import com.ainsigne.mobilesocialblogapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface SampleInjector {
    fun inject(fragment: SampleFragment)
}


/**
 * SampleInjector injector implementation of the protocol template for injection
 **/
class SampleInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : SampleFragment generated by the MVPTemplate
     **/
    fun inject(fragment: SampleFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter =
            SamplePresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
