package com.ainsigne.mobilesocialblogapp.ui.chat

import com.ainsigne.mobilesocialblogapp.data.DataInjector
import com.ainsigne.mobilesocialblogapp.manager.ServicesInjector
import com.ainsigne.mobilesocialblogapp.manager.APIManager
import com.ainsigne.mobilesocialblogapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface ChatInjector {
    fun inject(fragment: ChatFragment)
}


/**
 * ChatInjector injector implementation of the protocol template for injection
 **/
class ChatInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : ChatFragment generated by the MVPTemplate
     **/
    fun inject(fragment: ChatFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter = ChatPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
