package com.ainsigne.mobilesocialblogapp.ui.optionalsignup

import com.ainsigne.mobilesocialblogapp.data.DataInjector
import com.ainsigne.mobilesocialblogapp.manager.ServicesInjector
import com.ainsigne.mobilesocialblogapp.manager.APIManager
import com.ainsigne.mobilesocialblogapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface OptionalSignupInjector {
    fun inject(fragment: OptionalSignupFragment)
}


/**
 * OptionalSignupInjector injector implementation of the protocol template for injection
 **/
class OptionalSignupInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : OptionalSignupFragment generated by the MVPTemplate
     **/
    fun inject(fragment: OptionalSignupFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter =
            OptionalSignupPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
