package com.ainsigne.mobilesocialblogapp.ui.profile

import com.ainsigne.mobilesocialblogapp.data.DataInjector
import com.ainsigne.mobilesocialblogapp.manager.ServicesInjector
import com.ainsigne.mobilesocialblogapp.manager.APIManager
import com.ainsigne.mobilesocialblogapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface ProfileInjector {
    fun inject(fragment: ProfileFragment)
}


/**
 * ProfileInjector injector implementation of the protocol template for injection
 **/
class ProfileInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : ProfileFragment generated by the MVPTemplate
     **/
    fun inject(fragment: ProfileFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter =
            ProfilePresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
