package com.ainsigne.mobilesocialblogapp.ui.signup

import com.ainsigne.mobilesocialblogapp.data.DataInjector
import com.ainsigne.mobilesocialblogapp.manager.ServicesInjector
import com.ainsigne.mobilesocialblogapp.manager.APIManager
import com.ainsigne.mobilesocialblogapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface SignupInjector {
    fun inject(fragment: SignupFragment)
}


/**
 * SignupInjector injector implementation of the protocol template for injection
 **/
class SignupInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : SignupFragment generated by the MVPTemplate
     **/
    fun inject(fragment: SignupFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter =
            SignupPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
